### ISSUE TITLE
Trouble with WHAM input

### ISSUE THREAD

**Issue by cmstaley** [ruggleslab/jukebox#1]
Hi, I'm trying to input files into WHAM from Humann2. I've tried creating the input files using the humann_2_wham python script (input3) as well as manually (input 4) using both uniref90 and GO annotations, and the web interface keeps giving me an 'inappropriate format' error. These seem to match the sample information as well as the supplemental file from your paper. Please advise.

[wham_input4.txt](https://github.com/ruggleslab/jukebox/files/2233348/wham_input4.txt)
[wham_input3.txt](https://github.com/ruggleslab/jukebox/files/2233349/wham_input3.txt)

**Comment by jcooperdevlin** [comment]
As demonstrated in the manuscript, the differential abundance calculation relies on an assumption of raw count data. It appears the provided data is in the form of reads per kilobase.
For simplicity, I have rounded the input to remove the decimal values, and while this is an adequate representation in order to use WHAM! it is highly recommended to convert the reads per kilobase values into relative abundances and then use the total number of mapped reads to accurately estimate the counts. The number of mapped reads is readily available in the HUMANn2 output files, but I am happy to help with the count estimation.

[wham_input3_counts.txt](https://github.com/ruggleslab/jukebox/files/2233566/wham_input3_counts.txt)
[wham_input4_counts.txt](https://github.com/ruggleslab/jukebox/files/2233567/wham_input4_counts.txt)
