### ISSUE TITLE
RPK or CPM

### ISSUE THREAD

**Issue by lmanchon** [ruggleslab/jukebox#4]
--Hi,

again me for other question: do you think is best to feed wham with RPK or CPM counts ?
and last question: is there a way to add metadata such as concentration per condition, time point ...

thank you --

**Comment by jcooperdevlin** [comment]
As demonstrated in the manuscript, the differential abundance calculation relies on an assumption of raw count data. In order to use WHAM! it is recommended to generate relative abundance tables and then use the total number of mapped reads in each sample to accurately estimate the counts. The number of mapped reads is readily available in the HUMANn2 output files, but I am happy to help with the count estimation.

**Comment by lmanchon** [comment]
okay thank you; And for my second question i asked you:
is there a way to add metadata such as concentration per condition, time point ?

**Comment by jcooperdevlin** [comment]
You can group your samples within the application, but the grouping is performed manually by the user.
